{
 "title": "Per device Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instanceName", "label": "instance name", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Network Usage & QoS",
   "type": "timeseries",
   "description": "Stacked graph of Packets received, Packets sent, errors, and drops",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "dropInRate{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "packetsRecvRate{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dropOutRate{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "errorInRate{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "packetsSentRate{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "errorOutRate{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuCount{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpuCountLogical{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Available RAM and used RAM",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "usedMemory{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "availableMemory{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent storage used",
   "type": "gauge",
   "description": "percent of all mounted storages used",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "percentDiskUsed{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dlSpeed{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ulSpeed{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Storage space",
   "type": "stat",
   "description": "Available storage space across all mounted storages",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "totalDisk{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "usedSwap{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "availableSwap{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total RAM and Storage on the device",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "totalMemory{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "totalSwap{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Data used since last reboot",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bytesRecv{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bytesSent{instance=\"$instanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}